### ISSUE TITLE
Suggestion: leverage data formats

### ISSUE THREAD

**Issue by Beanow** [rseng/good-first-issues#2]
Noticing some parsing of the txt file is happening:
https://github.com/rseng/good-first-issues/blob/266448bc9d061e1e9a6326f4f6698c98f42b5b6c/scripts/generate-first-issues.py#L39-L41

JSON/YAML could probably make this easier and self-documenting:

```yaml
# json style
[
  {
    "owner": "organization",
    "name": "example-repo",
    "tags": ["hello", "world"]
  }
]

# yaml style
- owner: organization
  name: example-repo
  tags: [hello, world]
```

Likewise, I think it would be really useful to have an option to produce data output. Rather than directly going to front matter + markdown. Even if just internally in the python scripts.

Here's some pseudo code of what I mean in terms of interfaces.

```js
type Filename = string;
type MarkdownContent = string;

interface ScriptFunctions {
  fetchRepos(path: Filename): Repository[];
  fetchIssues(repos: Repository[]): Map<Repository, Issue[]>;
  templateIssues(data: Map<Repository, Issue[]>): Map<Filename, MarkdownContent>;
  writeMarkdownFiles(files: Map<Filename, MarkdownContent>);
}
```

This would make it trivial to support writing JSON data out instead of MD files :]
